# Site settings
title: Burns Haven
email: bookings@burnshaven.be
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/Burns_Haven" # the subpath of your site, e.g. /blog/
url: "https://awwerbro.github.io/Burns_Haven/" # the base hostname & protocol for your site

twitter_username:
github_username: "awwerbro"

# Build settings
markdown: kramdown
