# Site settings
title: Burns Haven
email: bookings@burnshaven.be
description: > # this means to ignore newlines until "baseurl:"
baseurl: "https://github.com/awwerbro/Burns_Haven/tree/master/" # the subpath of your site, e.g. /blog/
url: "https://github.com/awwerbro/Burns_Haven" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
